### ISSUE TITLE
Error initializing the application: net/kencochrane/raven/event/Event$Level

### ISSUE THREAD

**Issue by ilopmar** [agorapulse/grails-sentry#15]
I'm using the last version of the plugin (6.0.0.4) and Grails 2.5.0 and when I execute `run-app` I get the following error:

```
| Error 2015-04-23 09:03:09,987 [localhost-startStop-1] ERROR context.GrailsContextLoaderListener  - Error initializing the application: net/kencochrane/raven/event/Event$Level
Message: net/kencochrane/raven/event/Event$Level
    Line | Method
->> 2701 | privateGetDeclaredMethods in java.lang.Class
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|   1975 | getDeclaredMethods        in     ''
|    266 | run . . . . . . . . . . . in java.util.concurrent.FutureTask
|   1142 | runWorker                 in java.util.concurrent.ThreadPoolExecutor
|    617 | run . . . . . . . . . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run                       in java.lang.Thread
Caused by ClassNotFoundException: net.kencochrane.raven.event.Event$Level
->>  381 | findClass                 in java.net.URLClassLoader
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    424 | loadClass                 in java.lang.ClassLoader
|    357 | loadClass . . . . . . . . in     ''
|   2701 | privateGetDeclaredMethods in java.lang.Class
|   1975 | getDeclaredMethods . . .  in     ''
|    266 | run                       in java.util.concurrent.FutureTask
|   1142 | runWorker . . . . . . . . in java.util.concurrent.ThreadPoolExecutor
|    617 | run                       in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run . . . . . . . . . . . in java.lang.Thread
```

Is this a know issue?

**Comment by benorama** [comment]
There is some strange class loading issues with this lib. But I have not tested it against Grails 2.5.
I'm currently migrating the plugin to Grails 3 and LogBack.
If I might have a look on this this next week or fix/pull request welcome ;)

**Comment by lmivan** [comment]
Thank you.

**Comment by benorama** [comment]
Hi Ivan,

I could not reproduce the issue on two of our apps that I've migrated to Grails 2.5.0.
Is it a blank new app or an existing app?
Which JVM do you use?

I'm running:
```
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
```

**Comment by lmivan** [comment]
It's an existing app and I'm using:

```
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode
```

I could try with a new app to see if it happen in my environment.

**Comment by anujku** [comment]
@lmivan by any chance is it related to the Intellij ? I have seen classNotFound exceptions thanks to Intellij 14.0.11 or something version which was later solved by them.

**Comment by lmivan** [comment]
@anujku: No, I always run my grails applications from the command line.

**Comment by rblazquez** [comment]
java.lang.NoClassDefFoundError: net/kencochrane/raven/event/Event$Level

Same problem here ... something new about this?

This is:

java version "1.7.0_71"
Java(TM) SE Runtime Environment (build 1.7.0_71-b14)
Java HotSpot(TM) 64-Bit Server VM (build 24.71-b01, mixed mode)

AND:

Grails version: 2.4.3

**Comment by benorama** [comment]
@rblazquez no, we have not found the source of this issue, which occurs under certain conditions on existing apps.

**Comment by smallufo** [comment]
I am having the same exception 
```
[ERROR] 2016-01-22 14:01:53 context.GrailsContextLoaderListener - Error initializing the application: net/kencochrane/raven/event/Event
java.lang.NoClassDefFoundError: net/kencochrane/raven/event/Event
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: net.kencochrane.raven.event.Event
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

env 
```
grails 2.5.3

$ java -version
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)
```

**Comment by ocomsoft** [comment]
I am getting the same on Grails 2.3.11 and 
java version "1.7.0_91"
OpenJDK Runtime Environment (IcedTea 2.6.3) (7u91-2.6.3-0ubuntu0.15.04.1)
OpenJDK Server VM (build 24.91-b01, mixed mode)

**Comment by mhuebner** [comment]
Having the same issue

**Comment by Nr9** [comment]
Same issue!

**Comment by dbpfindexp** [comment]
Anyone have a solution for this?  I am trying with grails 2.5.3 and having the issue.

**Comment by dbpfindexp** [comment]
Found the solution - disabled forked grails execution in your Config.groovy.

**Comment by benorama** [comment]
Glad you found the solution !
